export const FORM_DATA = {
  content: [
    {
      formTitle: 'Personal Information',
      labelText: 'First Name',
      basicInput: false,
      inputType: 'text',
      placeholder: 'John',
      name: 'first-name',
      required: 'required',
      id: 'first-name',
    },
    {
      labelText: 'Last Name',
      basicInput: false,
      inputType: 'text',
      placeholder: 'Doe',
      name: 'last-name',
      required: 'required',
      id: 'last-name',
    },
    {
      labelText: 'Professional title',
      basicInput: false,
      inputType: 'text',
      placeholder: 'Software Developer',
      name: 'professional-title',
      required: 'required',
      id: 'professional-title',
    },
    {
      labelText: 'Summary',
      basicInput: true,
      inputType: 'text',
      placeholder: 'A summary of your professional experience',
      name: 'summary',
      required: 'required',
      id: 'summary',
    },
    {
      formTitle: 'Education',
      labelText: 'Education',
      basicInput: false,
      inputType: 'text',
      placeholder: 'education',
      name: 'education',
      required: 'required',
      id: 'education',
    },
  ],
  customize: [
    {
      formTitle: 'Customize',
      labelText: 'Font Size',
      basicInput: false,
      inputType: 'range',
      placeholder: 'Font Size',
      name: 'font-size',
      required: 'required',
      id: 'font-size',
    },
    {
      labelText: 'Font Color',
      basicInput: false,
      inputType: 'color',
      placeholder: 'Font Color',
      name: 'font-color',
      required: 'required',
      id: 'font-color',
    },
    {
      labelText: 'Background Color',
      basicInput: false,
      inputType: 'color',
      placeholder: 'Background Color',
      name: 'background-color',
      required: 'required',
      id: 'background-color',
    },
  ],
};
